DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;

CREATE TABLE categories (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1000),
  price DECIMAL(10,2) NOT NULL,
  in_stock BOOLEAN NOT NULL,
  category_id BIGINT,
  CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
